---
deployment:
  tasks:
    # Define the deployment path inside public_html
    - export DEPLOYPATH=/home/crmore/public_html/backend.crmore.com

    # Navigate to the deployment path
    - cd $DEPLOYPATH

    # Pull the latest code from GitHub
    - git pull origin main

    # Install dependencies
    - npm install --production || echo "npm install failed"

    # Ensure all images are copied
    - /bin/cp -R images $DEPLOYPATH/images || echo "Image copy failed"

    # Restart the backend application
    - pm2 restart server.js || pm2 start server.js
